.ds q \N'34'
.TH compton 1
.SH NAME
compton \- a compositor for X11
.SH SYNOPSIS
.nf
.B compton [\-d display] [\-r radius] [\-o opacity] [\-l left-offset] [\-t top-offset] [\-i opacity] [\-e opacity] [\-cCfFS]
.fi
.SH DESCRIPTION
.B compton
is a compositor based on Dana Jansens' version of xcompmgr (which itself was
written by Keith Packard). It includes many improvements over the original
xcompmgr, including window frame opacity, inactive window transparency,
and shadows on argb windows.
.SH OPTIONS
.TP
.BI \-d\ display
Specifies the display to manage.
.TP
.BI \-r\ radius
Specifies the blur radius for client-side shadows.
.TP
.BI \-o\ opacity
Specifies the opacity for client-side shadows.
.TP
.BI \-l\ left-offset
Specifies the left offset for client-side shadows.
.TP
.BI \-t\ top-offset
Specifies the top offset for client-side shadows.
.TP
.BI \-I\ fade-in-step
Specifies the opacity change between steps while fading in.
.TP
.BI \-O\ fade-out-step
Specifies the opacity change between steps while fading out.
.TP
.BI \-D\ fade-delta
Specifies the time (in milliseconds) between steps in a fade.
.TP
.BI \-c
Enable client-side shadows on windows.
.TP
.BI \-f
When \-c is specified, enables a smooth fade effect for transient windows like
menus, and for all windows on hide and restore events.
.TP
.BI \-C
When \-c is specified, attempts to avoid painting shadows on panels and docks.
.TP
.BI \-F
When \-f is specified, also enables the fade effect when windows change their
opacity, as with transset(1).
.TP
.BI \-i\ opacity
Specifies inactive window transparency. (0.1 - 1.0)
.TP
.BI \-e\ opacity
Specifies window frame transparency. (0.1 - 1.0)
.TP
.BI \-S
Enables synchronous operation.  Useful for debugging.
.SH BUGS
Please report any you find to https://github.com/chjj/compton.
.SH AUTHORS
xcompmgr, originally written by Keith Packard, with contributions from
Matthew Allum, Eric Anholt, Dan Doel, Thomas Luebking, Matthew Hawn,
Ely Levy, Phil Blundell, and Carl Worth.
Compton by Christopher Jeffrey, based on Dana Jansens' original work.
